all:
	ap_plugins_enabled:
		- apAuthSplashOnlyPlugin
	ap_modules_enabled:
		- apAuthSplashOnlyLogin
	config_options:
		main_url: 'http://weibo.com/mlyinxiang'
		site_name: '麻香传奇 - 免费无线网路 - 登陆'
		sms_url: 'http://192.168.7.111'